version: '3'

services:

    gin:
        build: ./gin
        container_name: api
        volumes:
            - ../api:/mnt/api
        ports:
            - 3000:3000
        tty: true
        working_dir: /mnt/api
        # command: go mod init example.com/m
        command: go run main.go
