version: '3'

services:

    gin:
        build: ./gin
        container_name: api
        volumes:
            - ../api:/mnt/api
        ports:
            - 3000:3000
        tty: true
        working_dir: /mnt/api

    db:
        image: mysql:5.7
        container_name: db
        environment:
            MYSQL_DATABASE: database
            MYSQL_USER: user
            MYSQL_PASSWORD: password
            MYSQL_ROOT_PASSWORD: root
            TZ: Asia/Tokyo
        volumes:
            - ./mysql/my.cnf:/etc/mysql/my.cnf