version: '3'

services:
    gin:
        build: ./gin
        volumes:
            - ../api:/mnt/api
        ports:
            - 8080:8080
        tty: true
        working_dir: /mnt/api
        command: go run main.go